<?php if ( $this->pageCount > 1 ): ?>
    <div class="wp-pagenavi">
        <?php if (isset($this->previous)): ?>
            <a href="<?= $this->url(array("page" => $this->previous)) ?>" class="prev page-numbers"><<</a>
        <?php endif; ?>
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?= $this->url(array("page" => $page)) ?>" class="page-numbers"><?= $page; ?></a>
            <?php else: ?>
                <span class="page-numbers current"><?= $page; ?></span>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php if (isset($this->next)): ?>
            <a href="<?= $this->url(array("page" => $this->next)) ?>" class="next page-numbers">»</a>
        <?php endif; ?>
    </div>
<?php endif; ?>