<!DOCTYPE html>
<html lang="uk">
<head>
    <title><?php echo $this->title; ?></title>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
    <meta name="description" content="<?= $this->description ?>"/>
    <meta name="keywords" content="<?= $this->keywords ?>"/>

    <script type="text/javascript" src="/static/default/js/jquery-1.9.1.min.js"></script>
    <script type="text/javascript" src="/static/default/js/script.js"></script>
    <?=$this->headScript()?>
</head>
<body>
    <?php echo $this->partial('blocks/header.phtml', array (
                                                           'menu' => $this->menu,
                                                           'blocks' => $this->blocks,
                                                           'siteSetings' => $this->siteSetings
                                                     )) ?>
    <?php echo $this->layout()->content ?>

    <?php echo $this->partial('blocks/footer.phtml', array (
                                                           'blocks'      => $this->blocks,
                                                           'siteSetings' => $this->siteSetings
                                                     )) ?>
</body>
</html>
