<!DOCTYPE html>
<html lang="uk">
<head>
    <title><?php echo $this->title; ?></title>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
    <meta name="description" content="<?= $this->description ?>"/>
    <meta name="keywords" content="<?= $this->keywords ?>"/>

    <meta name="google-site-verification" content="Yvr5LTXabsjsZJsakV0HmsIQqDxk16OvXavhFbcokX0" />
    <meta name='yandex-verification' content='543232000086a5ad' />

    <meta content="width=device-width, target-densityDpi=device-dpi" name="viewport" />
    <link type="text/css" rel="stylesheet" href="/static/default/css/style.css" media="all"/>

    <script type="text/javascript" src="/static/default/js/jquery.min.js"></script>
    <script type="text/javascript" src="/static/default/js/script.js"></script>
    <?=$this->headScript()?>
</head>
<body>
    <div id="wrapper">
        <?php echo $this->partial('blocks/menu.phtml', array (
                                                             'menu' => $this->menu,
                                                             'blocks' => $this->blocks,
                                                             'siteSetings' => $this->siteSetings
                                                       )) ?>
        <div id="main-container">
            <div class="wrapper">

                <div class="left-sidebar">
                    <?php echo $this->layout()->content ?>
                </div>
                <div class="right-sidebar">
                    <? $children = $this->children?$this->children:array();?>
                    <? if (!empty($children)):  ?>
                        <!--noindex-->
                        <div class="pin-article">
                            <div class="article">
                                <div class="title">Рубрики:</div>
                                <div class="tagcloud">
                                    <? foreach ($children as $cat): ?>
                                        <? $catContent = $cat->getContent()->getFields(); ?>
                                        <a rel="nofollow" class="tag-link" href="<?=$cat->getRoute()->geturl();?>"><?=$catContent['name']->getFieldtext();?></a>
                                    <? endforeach; ?>
                                </div>
                            </div>
                        </div>
                        <!--/noindex-->
                    <? endif; ?>
                    <div class="pin-article">
                        <div class="article">
                            <div class="title">Archives</div>
                            <ul>
                                <li><a href="#">December 2013</a></li>
                                <li><a href="#">September 2013</a></li>
                                <li><a href="#">August 2013</a></li>
                                <li><a href="#">May 2013</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="pin-article">
                        <div class="article">
                            <div class="title">Recent comments</div>
                            <ul>
                                <li>alexvtn on <a href="#">Video Post</a></li>
                                <li>alexvtn on <a href="#">Video Post</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="clr"></div>
            </div>
        </div>
        <?php echo $this->partial('blocks/footer.phtml', array (
                                                               'blocks'      => $this->blocks,
                                                               'siteSetings' => $this->siteSetings,
                                                               'text' => $this->text
                                                         )) ?>
    </div>
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
        (function (d, w, c) {
            (w[c] = w[c] || []).push(function() {
                try {
                    w.yaCounter24749843 = new Ya.Metrika({id:24749843,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true});
                } catch(e) { }
            });

            var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
            s.type = "text/javascript";
            s.async = true;
            s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

            if (w.opera == "[object Opera]") {
                d.addEventListener("DOMContentLoaded", f, false);
            } else { f(); }
        })(document, window, "yandex_metrika_callbacks");
    </script>
    <noscript><div><img src="//mc.yandex.ru/watch/24749843" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
</body>
</html>
