<?= $this->partial('blocks/menus/top.phtml'); ?>
<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<script src="/static/admin/js/fileuploader.js" type="text/javascript"></script>
<link type="text/css" title="stylesheet" href="/static/admin/css/fileuploader.css" rel="stylesheet"/>
<script>
    function setUrl(ele) {
        $('#url_category').val($('#opt_'+$(ele).val()).data('url'));
    }
    function initUploaderWall(options,idPhoto){
        
        initComplete = function(id, fileName, responseJSON) {
            var data = responseJSON;
            
            if (data.status == false) {
               ShowPopUp('Can not upload image now');
            } else {
                $('#previewImage'+idPhoto).removeClass('hide').attr('href', decodeURIComponent((data.path + '').replace(/&amp;/g, '&')) + '&t=' + new Date().getTime());
                $('#idPhoto'+idPhoto).val(data.idPhoto);
            }
        }

        new qq.FileUploader({
            element: document.getElementById(options.upload_button_id),
            action: options.action, 
            debug: true,
            button_label: options.button_label,
            onComplete: initComplete,
            messages: options.messages,
            showMessage: function(message) {
                alert(message);
            },
            onProgress: function(id, fileName, loaded, total){
                
            }
        }); 

        return false;
    }

     $(document).ready(function(){
        initUploaderWall({
            'upload_button_id':'file_uploader1',
            'action': '<?=$this->url(array('idPhoto'=>$this->idPhoto1),'admin-photo-upload')?>',
            'button_label': 'Загрузить'
        },1);
    });
</script>
<?
if( isset($this->photo1) )
    $photoPath1 = trim($this->photo1->getPhotoPath());
else 
    $photoPath1 = '';
?>
<form action="<?= $this->url() ?>" method="post" id="PageForm">
    <table class="zebra edit">
        <tr class="grey">
            <td width="193" class="first">URL:</td>
            <td>
                <input name="url_category" id="url_category" style="width:255px" type="text" class="field" value="<?= (isset($_POST['url_category'])) ? $_POST['url_category'] : '' ?>"/>
                <input name="realName"  type="text" class="field" style="background-color: #F2F2F2; width:7px;" value="/"  disabled="disabled"/>
                <input name="url" style="width:255px" type="text" class="field" value="<?= (isset($_POST['url'])) ? $_POST['url'] : '' ?>" />
            </td>
        </tr>
        <tr class="">
            <td width="193" class="first">Категория:</td>
            <td>
                <select name="category" multiple="true" onchange="setUrl(this)">
                    <option value="0"
                            id="opt_0"
                            data-url=""
                        >Черновик</option>
                    <? foreach ($this->categoryList->data as $category): ?>
                        <? $name = Application_Model_Kernel_Content_Fields::getFieldByIdContentAndNameField($category->getContent()->getId(), 'name')->getFieldText(); ?>
                        <option value="<?=$category->getId()?>"
                                data-url="<?=$category->getRoute()->getUrl();?>"
                                id="opt_<?=$category->getId()?>"
                        <? if ($this->edit && $this->post->getCurrentCategory()->getId() == $category->getId()): ?>selected="selected"<? endif; ?>
                            ><?=$name?></option>
                    <? endforeach; ?>
                </select>
            </td>
        </tr>
        <tr class="">
            <td width="193" class="first">Preview:
                <a href="<?if ($this->idPhoto1 === 0 || empty($photoPath1) ): ?>/static/admin/images/nobg.png<? else: echo Application_Model_Kernel_Photo::getById($this->idPhoto1)->getPath('210:130'); endif ?>" target="_blank" id="previewImage1" class="preview <? if ($this->idPhoto1 === 0 || empty($photoPath1) ): ?>hide<? endif ?>" title="">
                    <img src="/static/admin/images/picture.png" alt="">
                </a>
            </td>
            <td>
                <div id="file_uploader1"></div>
            </td>
        </tr>
    </table>
    <div id="tabs">
		<?php if (sizeof($this->langs) > 1): ?>
			<ul>
				<?php foreach ($this->langs as $lang): ?>
					<li><a href="#<?=$lang->getIsoName()?>"><?=$lang->getFullName()?></a></li>
				<?php endforeach ?>
			</ul>
		<?php endif ?>
		<?php foreach ($this->langs as $lang): ?>
			<div id="<?=$lang->getIsoName()?>"> 
				<table class="zebra edit">
					<tr class="grey">
						<td width="193" class="first">Название:</td>
						<td><input name="content[<?=$lang->getId()?>][name]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['name'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['name']) : ''?>" /></td>
					</tr>
					<tr class="">
						<td width="193" class="first">Титл:</td>
						<td><input name="content[<?=$lang->getId()?>][title]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['title'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['title']) : ''?>" /></td>
					</tr>
					<tr class="grey">
						<td width="193" class="first">Дескрипшин:</td>
						<td><input name="content[<?=$lang->getId()?>][description]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['description'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['description']) : ''?>" /></td>
					</tr>
					<tr class="">
						<td width="193" class="first">Кейвордс:</td>
						<td><input name="content[<?=$lang->getId()?>][keywords]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['keywords'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['keywords']) : ''?>" /></td>
					</tr>
					<tr class="grey">
						<td width="193" class="first">Основной текст:</td>
						<td>
							<textarea  id="textareas_<?=$lang->getIsoName()?>" rows='10' class='content' cols='40' name="content[<?=$lang->getId()?>][content]" tabindex='2' ><?=(isset($_POST['content'][$lang->getId()]['content'])) ? $_POST['content'][$lang->getId()]['content'] : ''?></textarea>
						</td>
					</tr>
				</table>
			</div> 
		<?php endforeach ?>
	</div>
    <table>
        <tr class="grey">
            <td colspan="2">
                <div class="m10 centerButton">
                    <input id="idPage" type="hidden" name="idPage" value="<?= $this->idPage ?>" />
                    <input id="idPhoto1" type="hidden" name="idPhoto1" value="<?=$this->idPhoto1?>" />
                    <a href="javascript:SubmitPageFrom();" class="button_blue">Сохранить</a>
                    <a href="<?=$this->url(array('page'=>1, 'cat'=>$this->cat),'admin-post-index') ?>" class="button_grey">Отменить</a>
                </div>
            </td>
        </tr>
    </table>
</form>
<input id="uploadUrl" type="hidden" value="<?=$this->url(array(),'admin-photo-upload')?>"/>