<? $categoryList =  Application_Model_Kernel_Category::getMainCategoryList(); ?>
<div class="footer">
    <div class="top-footer">
        <div class="container">
            <? /* <div class="widget-box">
                <div class="title">Site info</div>
                <div class="textwidget">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque et ultrices justo, non semper sapien. Sed adipiscing ipsum sit amet luctus accumsan. Cras rutrum volutpat eros sit amet blandit. </div>
            </div>
            <div class="widget-box">
                <div class="title">Credits</div>
                <div class="textwidget">In eget vulputate sapien. Nunc a lectus at nisi laoreet congue. Sed fermentum, nisi a consequat vulputate, ante lorem fringilla libero, vitae tristique justo nunc ac mi. Morbi ut massa eu purus mollis eleifend</div>
            </div> */ ?>
            <!--noindex-->
                <div class="widget-box">
                    <div class="title">Рубрики:</div>
                    <ul class="widget-category">
                        <? foreach ($categoryList->data as $category): ?>
                            <? $content = $category->getContent()->getFields(); ?>
                            <li class="cat-item">
                                <a rel="nofollow" title="<?=$content['name']->getFieldtext();?>" href="<?=$category->getRoute()->getUrl()?>"><?=$content['name']->getFieldtext();?></a>
                            </li>
                        <? endforeach; ?>
                    </ul>
                </div>
            <!--/noindex-->
            <? /* <div class="widget-box">
                <div class="title">Latest Tweets</div>
                <ul id="twitter_update_list">
                    <li>08/07/2013 - 09:27<br>Temi WordPress Gratis &ndash; Luglio 2013 <a target="_blank" title="http://t.co/6mQgMoANAO" href="http://t.co/6mQgMoANAO">http://t.co/6mQgMoANAO</a> via <a target="_blank" title="Follow WPinProgress" href="http://twitter.com/WPinProgress">@WPinProgress</a> <a target="_blank" title="Search #wordpressthemes" href="https://twitter.com/search?q=wordpressthemes">#wordpressthemes</a> <a target="_blank" title="Search #temiwordpress" href="https://twitter.com/search?q=temiwordpress">#temiwordpress</a> <a target="_blank" title="Search #wordpress" href="https://twitter.com/search?q=wordpress">#wordpress</a></li>
                </ul>
            </div> */ ?>
        </div>
    </div>
    <!--noindex-->
        <div class="bottom-footer">
            <div class="container">
                <div class="copyright">
                    <p>© <?=date('Y')?> Mentonol.com Все права защищены</p>
                </div>
            </div>
        </div>
    <!--/noindex-->
</div>