<?=$this->text;?>
<div class="footer">
    <div class="top-footer">
        <div class="container">
            <div class="widget-box">
                <h3 class="title">Site info</h3>
                <div class="textwidget">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque et ultrices justo, non semper sapien. Sed adipiscing ipsum sit amet luctus accumsan. Cras rutrum volutpat eros sit amet blandit. </div>
            </div>
            <div class="widget-box">
                <h3 class="title">Credits</h3>
                <div class="textwidget">In eget vulputate sapien. Nunc a lectus at nisi laoreet congue. Sed fermentum, nisi a consequat vulputate, ante lorem fringilla libero, vitae tristique justo nunc ac mi. Morbi ut massa eu purus mollis eleifend</div>
            </div>
            <div class="widget-box">
                <h3 class="title">Blog Category</h3>
                <ul class="widget-category">
                    <li class="cat-item"><a title="" href="#">Audio</a></li>
                    <li class="cat-item"><a title="" href="#">Gallery</a></li>
                    <li class="cat-item"><a title="" href="#">Travel</a></li>
                    <li class="cat-item"><a title="" href="#">Video</a></li>
                </ul>
            </div>
            <div class="widget-box">
                <h3 class="title">Latest Tweets</h3>
                <ul id="twitter_update_list">
                    <li>08/07/2013 - 09:27<br>Temi WordPress Gratis &ndash; Luglio 2013 <a target="_blank" title="http://t.co/6mQgMoANAO" href="http://t.co/6mQgMoANAO">http://t.co/6mQgMoANAO</a> via <a target="_blank" title="Follow WPinProgress" href="http://twitter.com/WPinProgress">@WPinProgress</a> <a target="_blank" title="Search #wordpressthemes" href="https://twitter.com/search?q=wordpressthemes">#wordpressthemes</a> <a target="_blank" title="Search #temiwordpress" href="https://twitter.com/search?q=temiwordpress">#temiwordpress</a> <a target="_blank" title="Search #wordpress" href="https://twitter.com/search?q=wordpress">#wordpress</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="bottom-footer">
        <div class="container">
            <div class="copyright">
                <p> Copyright Nova 2014 - Powered by <a target="_blank" href="http://www.wpinprogress.com/">WP in Progress</a> </p>
            </div>
        </div>
    </div>
</div>