<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<div class="left-sidebar">
    <div class="open-post pin-article">
        <div class="article">
            <h1 class="title"><?=$this->contentPage['name']->getFieldText()?></h1>
            <div class="line">
                <div class="entry-info">
                    <div class="entry-date"><strong>Posted on:</strong> 9 December 2013 <span class="sep">/</span></div>
                    <div class="entry-comments"><strong>Comments:</strong> <a href="#">2 comments</a><span class="sep">/</span></div>
                    <div class="entry-standard">
                        <strong>Categories: <a title="View all posts in Travel" href="#">Travel</a>, <a title="View all posts in Video" href="#">Video</a></strong>
                    </div>
                </div>
            </div>
            <? if ($this->post->getMainPhotoId()): ?>
                <div class="line">
                    <img src="<?=$this->post->getMainPhoto()->getPhotoImage();?>" width="720">
                </div>
            <? endif; ?>
            <?=$this->contentPage['content']->getFieldText()?>
        </div>
    </div>
</div>