services:
    main.news.admin.news:
        class: Acme\DemoBundle\Admin\ProjectAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Новости", label: "Новости" }
        arguments:
            - ~
            - Acme\DemoBundle\Entity\Project
            - SonataAdminBundle:CRUD