_welcome:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }

_welcome_login:
    pattern:  /hello
    defaults: { _controller: AcmeDemoBundle:Welcome:indexIn }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo_project:
    resource: "@AcmeDemoBundle/Controller/ProjectController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation

_workers:
    resource: "@AcmeDemoBundle/Controller/WorkersController.php"
    type:     annotation

_sites:
    resource: "@AcmeDemoBundle/Controller/SiteController.php"
    type:     annotation

_categories:
    resource: "@AcmeDemoBundle/Controller/CategoryController.php"
    type:     annotation