<?= $this->partial('blocks/menus/top.phtml'); ?>
<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<script>
    function setUrl(ele) {
        $('#url_category').val($('#opt_'+$(ele).val()).data('url'));
    }
</script>
<form action="<?= $this->url() ?>" method="post" id="PageForm">
    <table class="zebra edit">
        <tr class="grey">
            <td width="193" class="first">URL:</td>
            <td>
                <input name="url_category" id="url_category" style="width:255px" type="text" class="field" value="<?= (isset($_POST['url_category'])) ? $_POST['url_category'] : '' ?>"/>
                <input name="realName"  type="text" class="field" style="background-color: #F2F2F2; width:7px;" value="/"  disabled="disabled"/>
                <input name="url" style="width:255px" type="text" class="field" value="<?= (isset($_POST['url'])) ? $_POST['url'] : '' ?>" />
            </td>
        </tr>
        <tr class="">
            <td width="193" class="first">Категория:</td>
            <td>
                <select name="parent_id" multiple="true" onchange="setUrl(this)">
                    <option value="0"
                        id="opt_0"
                        data-url=""
                        >Главная</option>
                    <? foreach ($this->categoryList->data as $category): ?>
                        <? if ($this->category->getId() == $category->getId()) continue; ?>
                        <? $name = Application_Model_Kernel_Content_Fields::getFieldByIdContentAndNameField($category->getContent()->getId(), 'name')->getFieldText(); ?>
                        <option value="<?=$category->getId()?>"
                            data-url="<?=$category->getRoute()->getUrl();?>"
                            id="opt_<?=$category->getId()?>"
                            <? if ($this->category->getParentId() == $category->getId()): ?>selected="selected"<? endif; ?>
                            ><?=$name?></option>
                    <? endforeach; ?>
                </select>
            </td>
        </tr>
    </table>
    <div id="tabs">
		<?php if (sizeof($this->langs) > 1): ?>
			<ul>
				<?php foreach ($this->langs as $lang): ?>
					<li><a href="#<?=$lang->getIsoName()?>"><?=$lang->getFullName()?></a></li>
				<?php endforeach ?>
			</ul>
		<?php endif ?>
		<?php foreach ($this->langs as $lang): ?>
			<div id="<?=$lang->getIsoName()?>"> 
				<table class="zebra edit">
					<tr class="grey">
						<td width="193" class="first">Название:</td>
						<td><input name="content[<?=$lang->getId()?>][name]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['name'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['name']) : ''?>" /></td>
					</tr>
					<tr class="">
						<td width="193" class="first">Титл:</td>
						<td><input name="content[<?=$lang->getId()?>][title]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['title'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['title']) : ''?>" /></td>
					</tr>
					<tr class="grey">
						<td width="193" class="first">Дескрипшин:</td>
						<td><input name="content[<?=$lang->getId()?>][description]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['description'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['description']) : ''?>" /></td>
					</tr>
					<tr class="">
						<td width="193" class="first">Кейвордс:</td>
						<td><input name="content[<?=$lang->getId()?>][keywords]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['keywords'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['keywords']) : ''?>" /></td>
					</tr>
					<tr class="grey">
						<td width="193" class="first">Основной текст:</td>
						<td>
							<textarea  id="textareas_<?=$lang->getIsoName()?>" rows='10' class='content' cols='40' name="content[<?=$lang->getId()?>][content]" tabindex='2' ><?=(isset($_POST['content'][$lang->getId()]['content'])) ? $_POST['content'][$lang->getId()]['content'] : ''?></textarea>
						</td>
					</tr>
				</table>
			</div> 
		<?php endforeach ?>
	</div>
    <table>
        <tr class="grey">
            <td colspan="2">
                <div class="m10 centerButton">
                    <input id="idPage" type="hidden" name="idPage" value="<?= $this->idPage ?>" />
                    <a href="javascript:SubmitPageFrom();" class="button_blue">Сохранить</a>
                    <a href="<?=$this->url(array('page'=>1),'admin-salon-index') ?>" class="button_grey">Отменить</a>
                </div>
            </td>
        </tr>
    </table>
</form>
<input id="uploadUrl" type="hidden" value="<?=$this->url(array(),'admin-photo-upload')?>"/>