<?= $this->partial('blocks/menus/top.phtml'); ?>
<table class="zebra">
    <thead>
    <tr>
        <td style="width: 5%;"></td>
        <td>
        </td>
        <td></td>
        <td>
        </td>
        <td></td>
        <td></td>
    </tr>
    </thead>
    <?php if (count($this->categoryList->data)): ?>
        <?php $class = ''; ?>
        <tbody>
            <? foreach ($this->categoryList->data as $item): ?>
                <? ($class === 'grey') ? $class = '' : $class = 'grey'; ?>
                <? echo $this->categoryLi($item, $class);?>
                <? foreach ($item->getChildren()->data as $child): ?>
                    <? ($class === 'grey') ? $class = '' : $class = 'grey'; ?>
                    <? echo $this->categoryLi($child, $class);?>
                    <? foreach ($child->getChildren()->data as $child3): ?>
                        <? ($class === 'grey') ? $class = '' : $class = 'grey'; ?>
                        <? echo $this->categoryLi($child3, $class);?>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </tbody>
    <?php endif; ?>
</table>
<?= $this->paginationControl($this->categoryList->paginator, 'Sliding', 'blocks/paginator.phtml') ?>
<input id="statusUrl" type="hidden" value="<?= $this->url(array (), 'admin-category-status') ?>"/>